In [1]:
!pip install "numpy<2" --upgrade
# then restart your Jupyter kernel / Python process


In [41]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

In [5]:
df=pd.read_csv("synthetic_coffee_health_10000.csv")
df.head()

ID  Age  Gender  Country  Coffee_Intake  Caffeine_mg  Sleep_Hours  \
0   1   40    Male  Germany            3.5        328.1          7.5   
1   2   33    Male  Germany            1.0         94.1          6.2   
2   3   42    Male   Brazil            5.3        503.7          5.9   
3   4   53    Male  Germany            2.6        249.2          7.3   
4   5   32  Female    Spain            3.1        298.0          5.3   

  Sleep_Quality   BMI  Heart_Rate Stress_Level  Physical_Activity_Hours  \
0          Good  24.9          78          Low                     14.5   
1          Good  20.0          67          Low                     11.0   
2          Fair  22.7          59       Medium                     11.2   
3          Good  24.7          71          Low                      6.6   
4          Fair  24.1          76       Medium                      8.5   

  Health_Issues Occupation  Smoking  Alcohol_Consumption  
0           NaN      Other        0                    0  
1           NaN    Service        0                    0  
2          Mild     Office        0                    0  
3          Mild      Other        0                    0  
4          Mild    Student        0                    1

In [7]:
df.shape

(10000, 16)

In [9]:
df.isnull().sum()

ID                            0
Age                           0
Gender                        0
Country                       0
Coffee_Intake                 0
Caffeine_mg                   0
Sleep_Hours                   0
Sleep_Quality                 0
BMI                           0
Heart_Rate                    0
Stress_Level                  0
Physical_Activity_Hours       0
Health_Issues              5941
Occupation                    0
Smoking                       0
Alcohol_Consumption           0
dtype: int64

In [11]:
df['Health_Issues'].value_counts()

Health_Issues
Mild        3579
Moderate     463
Severe        17
Name: count, dtype: int64

In [13]:
df['Health_Issues']=df['Health_Issues'].fillna(df['Health_Issues'].mode()[0])

In [15]:
df.isnull().sum()

ID                         0
Age                        0
Gender                     0
Country                    0
Coffee_Intake              0
Caffeine_mg                0
Sleep_Hours                0
Sleep_Quality              0
BMI                        0
Heart_Rate                 0
Stress_Level               0
Physical_Activity_Hours    0
Health_Issues              0
Occupation                 0
Smoking                    0
Alcohol_Consumption        0
dtype: int64

In [17]:
df.dtypes

ID                           int64
Age                          int64
Gender                      object
Country                     object
Coffee_Intake              float64
Caffeine_mg                float64
Sleep_Hours                float64
Sleep_Quality               object
BMI                        float64
Heart_Rate                   int64
Stress_Level                object
Physical_Activity_Hours    float64
Health_Issues               object
Occupation                  object
Smoking                      int64
Alcohol_Consumption          int64
dtype: object

In [23]:
cat_features=[feature for feature in df.columns if df[feature].dtype=='object']
cat_features

['Gender',
 'Country',
 'Sleep_Quality',
 'Stress_Level',
 'Health_Issues',
 'Occupation']

In [25]:
le=LabelEncoder()
for cat_features in df.columns:
    df[cat_features]=le.fit_transform(df[cat_features])
print(df.head())    

   ID  Age  Gender  Country  Coffee_Intake  Caffeine_mg  Sleep_Hours  \
0   0   22       1        7             35         2784           45   
1   1   15       1        7             10          631           32   
2   2   24       1        2             53         3998           29   
3   3   35       1        7             26         2054           43   
4   4   14       0       15             31         2514           23   

   Sleep_Quality  BMI  Heart_Rate  Stress_Level  Physical_Activity_Hours  \
0              2   99          28             1                      145   
1              2   50          17             1                      110   
2              1   77           9             2                      112   
3              2   97          21             1                       66   
4              1   91          26             2                       85   

   Health_Issues  Occupation  Smoking  Alcohol_Consumption  
0              0           2        0            

In [27]:
x=df.drop(columns='Health_Issues',axis=1)

In [29]:
y=df['Health_Issues']

In [31]:
x

ID  Age  Gender  Country  Coffee_Intake  Caffeine_mg  Sleep_Hours  \
0        0   22       1        7             35         2784           45   
1        1   15       1        7             10          631           32   
2        2   24       1        2             53         3998           29   
3        3   35       1        7             26         2054           43   
4        4   14       0       15             31         2514           23   
...    ...  ...     ...      ...            ...          ...          ...   
9995  9995   32       0       10             21         1586           30   
9996  9996    0       0       18             34         2703           28   
9997  9997    8       1        4             16         1149           41   
9998  9998   22       0        5             34         2774           40   
9999  9999   24       0        2             29         2326           34   

      Sleep_Quality  BMI  Heart_Rate  Stress_Level  Physical_Activity_Hours  \
0                 2   99          28             1                      145   
1                 2   50          17             1                      110   
2                 1   77           9             2                      112   
3                 2   97          21             1                       66   
4                 1   91          26             2                       85   
...             ...  ...         ...           ...                      ...   
9995              1  155           0             2                      101   
9996              1   41          21             2                      116   
9997              2  101          16             1                      137   
9998              2   43          30             1                        1   
9999              2  131          22             1                       98   

      Occupation  Smoking  Alcohol_Consumption  
0              2        0                    0  
1              3        0                    0  
2              1        0                    0  
3              2        0                    0  
4              4        0                    1  
...          ...      ...                  ...  
9995           0        0                    1  
9996           3        0                    0  
9997           4        1                    1  
9998           4        0                    0  
9999           4        1                    0  

[10000 rows x 15 columns]

In [33]:
y

0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    0
9997    0
9998    0
9999    0
Name: Health_Issues, Length: 10000, dtype: int32

In [35]:
s=StandardScaler()
s.fit_transform(x)

array([[-1.73187761,  0.45284219,  0.87960545, ...,  0.00768361,
        -0.50062492, -0.65574494],
       [-1.7315312 , -0.17461136,  0.87960545, ...,  0.7191286 ,
        -0.50062492, -0.65574494],
       [-1.73118479,  0.63211463,  0.87960545, ..., -0.70376139,
        -0.50062492, -0.65574494],
       ...,
       [ 1.73118479, -0.8020649 ,  0.87960545, ...,  1.4305736 ,
         1.99750343,  1.52498317],
       [ 1.7315312 ,  0.45284219, -0.96250021, ...,  1.4305736 ,
        -0.50062492, -0.65574494],
       [ 1.73187761,  0.63211463, -0.96250021, ...,  1.4305736 ,
         1.99750343, -0.65574494]])

In [37]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [43]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [47]:
y_pred=dtc.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [51]:
print(accuracy_score(y_test,y_pred)*100)

99.8


In [53]:
print(confusion_matrix(y_test,y_pred))

[[2380    3    0]
 [   2  111    0]
 [   0    0    4]]


In [61]:
arr=np.array([[9995	,32,0,	10,	21,	1586,	30	,1	,155,	0	,2	,101,0,0,1]])
arr

array([[9995,   32,    0,   10,   21, 1586,   30,    1,  155,    0,    2,
         101,    0,    0,    1]])

In [63]:
y_pred1=dtc.predict(arr)
y_pred1

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])