1.IMPORT PYTHON LIBRARIES

In [15]:
import numpy as np
import pandas as pd

2.LOAD THE DATASET

In [18]:
data=pd.read_csv("traffic.csv")
data

Time  Date Day of the week  CarCount  BikeCount  BusCount  \
0     12:00:00 AM    10         Tuesday      31.0          0         4   
1     12:15:00 AM    10         Tuesday      49.0          0         3   
2     12:30:00 AM    10         Tuesday      46.0          0         3   
3     12:45:00 AM    10             NaN      51.0          0         2   
4      1:00:00 AM    10         Tuesday      57.0          6        15   
...           ...   ...             ...       ...        ...       ...   
2971  10:45:00 PM     9        Thursday      16.0          3         1   
2972  11:00:00 PM     9        Thursday      11.0          0         1   
2973  11:15:00 PM     9        Thursday      15.0          4         1   
2974  11:30:00 PM     9        Thursday      16.0          5         0   
2975  11:45:00 PM     9        Thursday      14.0          3         1   

      TruckCount  Total Traffic Situation  
0              4     39               low  
1              3     55               low  
2              6     55               low  
3              5     58               low  
4             16     94            normal  
...          ...    ...               ...  
2971          36     56            normal  
2972          30     42            normal  
2973          25     45            normal  
2974          27     48            normal  
2975          15     33            normal  

[2976 rows x 9 columns]

3.FUNCTIONS

In [21]:
data.head()

Time  Date Day of the week  CarCount  BikeCount  BusCount  \
0  12:00:00 AM    10         Tuesday      31.0          0         4   
1  12:15:00 AM    10         Tuesday      49.0          0         3   
2  12:30:00 AM    10         Tuesday      46.0          0         3   
3  12:45:00 AM    10             NaN      51.0          0         2   
4   1:00:00 AM    10         Tuesday      57.0          6        15   

   TruckCount  Total Traffic Situation  
0           4     39               low  
1           3     55               low  
2           6     55               low  
3           5     58               low  
4          16     94            normal

In [23]:
data.tail()

Time  Date Day of the week  CarCount  BikeCount  BusCount  \
2971  10:45:00 PM     9        Thursday      16.0          3         1   
2972  11:00:00 PM     9        Thursday      11.0          0         1   
2973  11:15:00 PM     9        Thursday      15.0          4         1   
2974  11:30:00 PM     9        Thursday      16.0          5         0   
2975  11:45:00 PM     9        Thursday      14.0          3         1   

      TruckCount  Total Traffic Situation  
2971          36     56            normal  
2972          30     42            normal  
2973          25     45            normal  
2974          27     48            normal  
2975          15     33            normal

In [25]:
data.shape

(2976, 9)

In [27]:
data.isnull().sum()

Time                 0
Date                 0
Day of the week      5
CarCount             2
BikeCount            0
BusCount             0
TruckCount           0
Total                0
Traffic Situation    6
dtype: int64

4.DATA IMPUTATION

In [30]:
data["Day of the week"]=data["Day of the week"].fillna(data["Day of the week"].mode()[0])
data["CarCount"]=data["CarCount"].fillna(data["CarCount"].median())
data["Traffic Situation"]=data["Traffic Situation"].fillna(data["Traffic Situation"].mode()[0])

In [32]:
data.isnull().sum()

Time                 0
Date                 0
Day of the week      0
CarCount             0
BikeCount            0
BusCount             0
TruckCount           0
Total                0
Traffic Situation    0
dtype: int64

In [34]:
data.dtypes

Time                  object
Date                   int64
Day of the week       object
CarCount             float64
BikeCount              int64
BusCount               int64
TruckCount             int64
Total                  int64
Traffic Situation     object
dtype: object

In [36]:
cat_features=[feature for feature in data.columns if data[feature].dtype=='object']
cat_features

['Time', 'Day of the week', 'Traffic Situation']

5.DATA ENCODING

In [39]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for cat_features in data.columns:
   data[cat_features]=le.fit_transform(data[cat_features])
print(data.head())

   Time  Date  Day of the week  CarCount  BikeCount  BusCount  TruckCount  \
0    16     9                5        25          0         4           4   
1    18     9                5        43          0         3           3   
2    20     9                5        40          0         3           6   
3    22     9                6        45          0         2           5   
4    24     9                5        51          6        15          16   

   Total  Traffic Situation  
0     18                  2  
1     34                  2  
2     34                  2  
3     37                  2  
4     73                  3  


In [40]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [41]:
x

Time  Date  Day of the week  CarCount  BikeCount  BusCount  TruckCount  \
0       16     9                5        25          0         4           4   
1       18     9                5        43          0         3           3   
2       20     9                5        40          0         3           6   
3       22     9                6        45          0         2           5   
4       24     9                5        51          6        15          16   
...    ...   ...              ...       ...        ...       ...         ...   
2971     7     8                4        10          3         1          36   
2972     9     8                4         5          0         1          30   
2973    11     8                4         9          4         1          25   
2974    13     8                4        10          5         0          27   
2975    15     8                4         8          3         1          15   

      Total  
0        18  
1        34  
2        34  
3        37  
4        73  
...     ...  
2971     35  
2972     21  
2973     24  
2974     27  
2975     12  

[2976 rows x 8 columns]

In [42]:
y

0       2
1       2
2       2
3       2
4       3
       ..
2971    3
2972    3
2973    3
2974    3
2975    3
Name: Traffic Situation, Length: 2976, dtype: int32

6.DATA NORMALIZATION

In [48]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit_transform(x)

array([[-1.13672002, -0.67082039,  0.89822066, ..., -0.78660412,
        -1.06818318, -1.25174526],
       [-1.06454732, -0.67082039,  0.89822066, ..., -0.85634118,
        -1.16250455, -0.98528289],
       [-0.99237462, -0.67082039,  0.89822066, ..., -0.85634118,
        -0.87954044, -0.98528289],
       ...,
       [-1.31715176, -0.78262379,  0.4004358 , ..., -0.99581532,
         0.91256559, -1.15182187],
       [-1.24497906, -0.78262379,  0.4004358 , ..., -1.06555238,
         1.10120833, -1.10186017],
       [-1.17280636, -0.78262379,  0.4004358 , ..., -0.99581532,
        -0.03064811, -1.35166864]])

7.SPLIT THE DATA

In [51]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [53]:
y_test.head

<bound method NDFrame.head of 673     3
2666    0
2049    0
2690    3
453     0
       ..
299     3
265     0
1599    3
2529    0
1866    1
Name: Traffic Situation, Length: 744, dtype: int32>

8.ALGORITHMS

In [56]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [58]:
y_pred=dt.predict(x_test)

In [60]:
y_pred

array([3, 0, 0, 3, 0, 1, 3, 0, 3, 2, 0, 3, 3, 0, 3, 3, 0, 3, 3, 3, 0, 3,
       0, 3, 1, 1, 3, 3, 0, 3, 3, 3, 3, 3, 3, 1, 3, 3, 0, 0, 2, 3, 1, 3,
       0, 3, 0, 3, 0, 2, 0, 3, 3, 3, 3, 0, 3, 2, 0, 1, 3, 3, 3, 1, 3, 3,
       1, 3, 3, 3, 0, 0, 0, 2, 0, 3, 3, 3, 0, 3, 3, 3, 3, 3, 1, 3, 3, 3,
       3, 3, 3, 1, 0, 3, 3, 1, 3, 3, 1, 3, 3, 1, 1, 3, 3, 1, 0, 0, 3, 0,
       1, 0, 2, 2, 3, 3, 0, 0, 3, 3, 0, 0, 1, 3, 3, 3, 3, 3, 3, 2, 0, 3,
       1, 0, 3, 3, 0, 2, 0, 1, 3, 3, 0, 0, 1, 0, 3, 3, 1, 3, 3, 0, 3, 1,
       0, 3, 1, 0, 3, 1, 3, 3, 3, 0, 2, 3, 3, 3, 0, 0, 0, 3, 3, 3, 3, 2,
       3, 0, 2, 1, 0, 1, 0, 3, 3, 1, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 2, 0,
       3, 3, 3, 2, 3, 3, 0, 1, 2, 3, 1, 3, 0, 2, 0, 3, 3, 2, 3, 0, 3, 3,
       3, 3, 3, 3, 0, 3, 3, 3, 0, 3, 3, 3, 1, 1, 3, 3, 3, 3, 3, 0, 1, 3,
       0, 0, 3, 2, 3, 0, 3, 3, 1, 3, 0, 3, 0, 3, 2, 1, 3, 2, 3, 3, 3, 3,
       3, 3, 0, 3, 3, 3, 2, 2, 3, 3, 0, 3, 3, 1, 3, 3, 3, 3, 0, 3, 3, 3,
       0, 3, 3, 1, 1, 1, 3, 3, 3, 0, 3, 3, 2, 0, 3,

9.MODEL PERFOMENCE

In [63]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9986559139784946


In [65]:
svm=SVC()
svm.fit(x_train,y_train)

SVC()

In [67]:
y_pred1=svm.predict(x_test)
y_pred1

array([3, 0, 0, 3, 0, 1, 3, 0, 3, 2, 0, 3, 3, 1, 3, 3, 0, 1, 3, 3, 0, 3,
       0, 3, 1, 0, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 2, 3, 1, 3,
       0, 3, 0, 3, 0, 3, 0, 3, 3, 3, 3, 0, 3, 3, 0, 1, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 1, 0, 0, 2, 0, 3, 1, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 1, 0, 3, 3, 1, 3, 3, 1, 3, 3, 3, 1, 3, 3, 1, 0, 0, 3, 0,
       1, 0, 2, 3, 3, 3, 0, 0, 3, 3, 0, 0, 1, 3, 3, 3, 3, 3, 3, 3, 0, 3,
       1, 0, 3, 3, 0, 2, 0, 1, 3, 3, 0, 0, 1, 0, 3, 3, 1, 3, 3, 0, 3, 1,
       0, 3, 1, 0, 3, 1, 3, 3, 3, 0, 2, 3, 3, 3, 0, 0, 0, 3, 3, 3, 3, 3,
       3, 0, 2, 1, 0, 1, 0, 3, 3, 0, 3, 3, 3, 3, 3, 2, 0, 3, 3, 3, 2, 0,
       3, 3, 3, 3, 2, 3, 0, 1, 2, 3, 1, 3, 0, 2, 0, 3, 3, 3, 3, 0, 3, 3,
       3, 3, 3, 3, 0, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 0, 1, 3,
       0, 0, 3, 2, 3, 0, 3, 3, 0, 3, 0, 3, 0, 3, 2, 1, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 3, 3, 3, 3, 2, 3, 3, 0, 3, 3, 1, 3, 3, 3, 3, 0, 3, 3, 3,
       0, 3, 3, 1, 1, 1, 3, 3, 3, 0, 0, 3, 2, 0, 3,

In [69]:
print(accuracy_score(y_test,y_pred))

0.9986559139784946


In [71]:
y_test

673     3
2666    0
2049    0
2690    3
453     0
       ..
299     3
265     0
1599    3
2529    0
1866    1
Name: Traffic Situation, Length: 744, dtype: int32

In [73]:
arr=np.array([[16,	9	,5	,25,	0	,4	,4	,18]])
arr

array([[16,  9,  5, 25,  0,  4,  4, 18]])

In [75]:
y=svm.predict(arr)
y

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([2])